<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Foodprint.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Foodprint.Core\Foodprint.Core.csproj" />
  </ItemGroup>

</Project>
