// <auto-generated />
using System;
using Foodprint.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Foodprint.Core.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Foodprint.Core.Domain.MealEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EatenAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MealGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PortionGrams")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PortionSize")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MealGroupId");

                    b.HasIndex("UserId", "EatenAt");

                    b.ToTable("MealEntries", t =>
                        {
                            t.HasCheckConstraint("CK_MealEntry_Portion", "(\"PortionSize\" IS NULL OR \"PortionGrams\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Foodprint.Core.Domain.MealEntryTag", b =>
                {
                    b.Property<Guid>("MealEntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("MealEntryId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("MealEntryTags");
                });

            modelBuilder.Entity("Foodprint.Core.Domain.MealGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RetiredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("MealGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "breakfast",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 2,
                            Key = "lunch",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 3,
                            Key = "dinner",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = 4,
                            Key = "snack",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = 5,
                            Key = "other",
                            SortOrder = 50
                        });
                });

            modelBuilder.Entity("Foodprint.Core.Domain.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Foodprint.Core.Domain.RegistrationLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CreatedByAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RegistrationLinks");
                });

            modelBuilder.Entity("Foodprint.Core.Domain.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Foodprint.Core.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Foodprint.Core.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Foodprint.Core.Domain.MealEntry", b =>
                {
                    b.HasOne("Foodprint.Core.Domain.MealGroup", "MealGroup")
                        .WithMany()
                        .HasForeignKey("MealGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Foodprint.Core.Domain.User", "User")
                        .WithMany("MealEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Foodprint.Core.Domain.MealEntryTag", b =>
                {
                    b.HasOne("Foodprint.Core.Domain.MealEntry", "MealEntry")
                        .WithMany("EntryTags")
                        .HasForeignKey("MealEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foodprint.Core.Domain.Tag", "Tag")
                        .WithMany("EntryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealEntry");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Foodprint.Core.Domain.Profile", b =>
                {
                    b.HasOne("Foodprint.Core.Domain.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Foodprint.Core.Domain.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Foodprint.Core.Domain.Session", b =>
                {
                    b.HasOne("Foodprint.Core.Domain.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Foodprint.Core.Domain.Tag", b =>
                {
                    b.HasOne("Foodprint.Core.Domain.User", "User")
                        .WithMany("Tags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Foodprint.Core.Domain.MealEntry", b =>
                {
                    b.Navigation("EntryTags");
                });

            modelBuilder.Entity("Foodprint.Core.Domain.Tag", b =>
                {
                    b.Navigation("EntryTags");
                });

            modelBuilder.Entity("Foodprint.Core.Domain.User", b =>
                {
                    b.Navigation("MealEntries");

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("Sessions");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
